### ISSUE TITLE
Could not find "_unload" in Free Loader's main.py 

### ISSUE THREAD

**Issue by hensou** [jwhitlow45/free-loader#6]
Installing and running the plugin on my steam deck gives me the following error:

```
Calling Loader unload function.
Attempting to unload with plugin Free Loader's "_unload" function.
Could not find "_unload" in Free Loader's main.py
```

OS Version: 3.5.17

**Comment by jwhitlow45** [comment]
Not seeing this on SteamOS 3.5.19 with Decky Loader 2.12.0. Could you try updating and letting me know if the issue is still occurring? Thanks.

**Comment by hensou** [comment]
This is working now, thanks a lot!
